const READING: PostPreview[] = [
  {
    type: "Reading",
    title: "정상 과로",
    author: "에린 L 켈리, 필리스 모엔",
    fileName: "Overload-How-Good-Jobs-Went-Bad-and-What-We-Can-Do-About-It",
    date: "2024-12-31",
  },
  {
    type: "Reading",
    title: "자유로부터의 도피",
    author: "에리히 프롬",
    fileName: "Escape-from-Freedom",
    date: "2024-12-09",
  },
  {
    type: "Reading",
    title: "정보가 너무 많아서",
    author: "캐스 R 선스타인",
    fileName: "Too-Much-Information",
    date: "2024-07-30",
  },
  {
    type: "Reading",
    title: "우리가 빛의 속도로 갈 수 없다면",
    author: "김초엽",
    fileName: "If-We-Cant-Go-at-the-Speed-of-Light",
    date: "2024-05-12",
  },
  {
    type: "Reading",
    title: "이펙추에이션",
    author: "사라스 사라스바티",
    fileName: "Effectuation-Elements-of-Entrepreneurial-Expertise",
    date: "2024-04-20",
  },
  {
    type: "Reading",
    title: "영혼의 미술관",
    author: "알랭 드 보통",
    fileName: "Art-as-Therapy",
    date: "2024-03-26",
  },
  {
    type: "Reading",
    title: "창조적 행위: 존재의 방식",
    author: "릭 루빈",
    fileName: "The-Creative-ACT",
    date: "2024-01-03",
  },
  {
    type: "Reading",
    title: "트렌드 코리아 2024",
    author: "김난도",
    fileName: "Trend-Korea-2024",
    date: "2023-12-26",
  },
  {
    type: "Reading",
    title: "키워드로 읽는 불평등 사회",
    author: "조형근",
    fileName: "Reading-Inequality-Through-Keywords",
    date: "2023-12-12",
  },
  {
    type: "Reading",
    title: "커뮤니티는 어떻게 브랜드의 무기가 되는가",
    author: "이승윤",
    fileName: "How-Does-a-Community-Become-a-Brands-Weapon",
    date: "2023-12-03",
  },
  {
    type: "Reading",
    title: "굿 퀘스천",
    author: "이와즈 교이치",
    fileName: "Good-Question",
    date: "2023-11-23",
  },
  {
    type: "Reading",
    title: "프루스트를 좋아하세요",
    author: "알랭 드 보통",
    fileName: "How-Proust-Can-Change-Your-Life",
    date: "2023-10-01",
  },
  {
    type: "Reading",
    title: "사피엔스",
    author: "유발 하라리",
    fileName: "Sapiens",
    date: "2023-09-23",
  },
  {
    type: "Reading",
    title: "타이탄의 도구들",
    author: "팀 페리스",
    fileName: "Tools-of-Titans",
    date: "2023-09-10",
  },
  {
    type: "Reading",
    title: "마음 가면",
    author: "브레네 브라운",
    fileName: "Daring-Greatly",
    date: "2023-09-01",
  },
  {
    type: "Reading",
    title: "달과 6펜스",
    author: "서머싯 몸",
    fileName: "The-Moon-and-Sixpence",
    date: "2023-08-20",
  },
  {
    type: "Reading",
    title: "물고기는 존재하지 않는다",
    author: "룰루 밀러",
    fileName: "Why-Fish-Dont-Exist",
    date: "2023-06-12",
  },
];

export default READING;
