const DEVELOPMENT: PostPreview[] = [
  {
    type: "Development",
    title: "SSR로 사용자 경험 향상시키기",
    fileName: "Enhancing-UX-with-SSR",
    date: "2024-12-29",
    description:
      "Server-Side Rendering(SSR)을 활용해 웹사이트의 SEO, 초기 로드 속도, 사용자 경험을 한 단계 끌어올리는 방법을 소개합니다. CSR과 SSR의 차이, 성능 실험 결과, 효율적인 혼합 전략 및 React와 최신 웹 기술을 활용한 최적화 사례까지, 실무에 바로 적용 가능한 인사이트를 제공합니다.",
    keywords: [
      "SSR",
      "Server-Side Rendering",
      "CSR",
      "Client-Side Rendering",
      "웹 성능 최적화",
      "SEO 강화",
      "초기 로드 속도",
      "FCP 단축",
      "LCP 개선",
      "TTFB 최적화",
      "React Streaming SSR",
      "웹 캐싱 전략",
      "사용자 경험 향상",
      "SEO 친화적 웹사이트",
      "실무 적용 사례",
      "최신 웹 기술",
    ],
  },
  {
    type: "Development",
    title: "웹 표준의 미래, WebNN으로 만나는 웹 AI",
    fileName: "Future-of-Web-Standards-Exploring-Web-AI-with-WebNN",
    date: "2024-12-27",
    description:
      "WebNN API를 활용해 브라우저에서 고성능 머신러닝 모델을 실행할 수 있는 방법과 WebAI 시대의 변화를 소개합니다. 최신 웹 표준을 통해 사용자 경험을 혁신하고 클라우드 의존성을 줄이는 WebNN의 가능성을 확인해보세요.",
    keywords: [
      "WebNN",
      "WebAI",
      "Frontend Development",
      "브라우저 머신러닝",
      "WebAI Summit",
      "웹 표준",
      "하드웨어 가속",
      "WebNN API",
      "온디바이스 AI",
      "WebAI 기술",
    ],
  },
  {
    type: "Development",
    title: "Zero Run Time CSS 도구들은 왜 컴포넌트 선언 형식이 아닐까?",
    fileName: "Why-Are-Zero-Run-Time-CSS-Tools-Not-Component-Based",
    date: "2024-12-09",
  },
  {
    type: "Development",
    title: "Paint 이전 Macro Task가 실행될 가능성과 React의 useEffect",
    fileName: "Possibility-of-Macro-Tasks-Being-Executed-Before-Paint-and-React-useEffect",
    date: "2024-11-28",
  },
  {
    type: "Development",
    title: "[Apollo Basic] Apollo Client를 이용하여 Supabase GraphQL 요청 보내기",
    fileName: "Apollo-Basic-Apollo-Client-Using-Supabase-GraphQL-Request",
    date: "2024-11-27",
  },
  {
    type: "Development",
    title: "[Settings] GraphQL과 Supabase, Apollo Client 설정",
    fileName: "GraphQL-and-GraphQL-Apollo-Settings",
    date: "2024-11-26",
  },
  {
    type: "Development",
    title: "Tanstack Query의 useQuery 캐싱 매커니즘 분석하기",
    fileName: "Analyzing-the-Caching-Mechanism-of-TanStack-Querys-useQuery",
    date: "2024-11-26",
  },
  {
    type: "Development",
    title: "PopoverMenu 컴포넌트의 createPortal과 합성 이벤트 문제 해결 및 자식 요소 컴포넌트 렌더러 만들기",
    fileName: "Popover-Menu-Create-Portal-Event-Fix-and-Child-Renderer",
    date: "2024-11-16",
  },
  {
    type: "Development",
    title: "크루루 서비스의 자동 로그인 문제와 Tanstack Query 캐싱 이슈 해결기",
    fileName: "Resolving-Auto-Login-Issues-and-TanStack-Query-Caching-Challenges-in-the-Cruru-Service",
    date: "2024-11-13",
  },
  {
    type: "Development",
    title: "Next.js vs Remix 뭐가 더 좋을까?",
    fileName: "Which-Is-Better-Nextjs-or-Remix",
    date: "2024-10-31",
  },
  {
    type: "Development",
    title: "디자인 시스템에 아토믹 디자인 패턴 도입하기",
    fileName: "Adopting-Atomic-Design-Pattern-in-a-Design-System",
    date: "2024-09-15",
  },
  {
    type: "Development",
    title: "옵저버 패턴과 Tanstack Query에서의 옵저버 패턴",
    fileName: "Observer-Pattern-and-the-Use-of-Observer-Pattern-in-TanStack-Query",
    date: "2024-04-08",
  },
];

export default DEVELOPMENT;
