name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Debug Secrets Value
        run: |
          echo "INSTAGRAM_ACCESS_TOKEN=${{ secrets.INSTAGRAM_ACCESS_TOKEN }}" || echo "INSTAGRAM_ACCESS_TOKEN is empty!"
          echo "GA_ID=${{ secrets.GA_ID }}" || echo "GA_ID is empty!"
          echo "NOTION_SECRET=${{ secrets.NOTION_SECRET }}" || echo "NOTION_SECRET is empty!"
          echo "NOTION_TOKEN_V2=${{ secrets.NOTION_TOKEN_V2 }}" || echo "NOTION_TOKEN_V2 is empty!"
          echo "NOTION_USER_ID=${{ secrets.NOTION_USER_ID }}" || echo "NOTION_USER_ID is empty!"        
          echo "NOTION_DATABASE_DEVELOPMENT_I=${{ secrets.NOTION_DATABASE_DEVELOPMENT_ID }}" || echo "NOTION_DATABASE_DEVELOPMENT_I is empty!"
          echo "NOTION_DATABASE_INSIGHTS_ID=${{ secrets.NOTION_DATABASE_INSIGHTS_ID }}" || echo "NOTION_DATABASE_INSIGHTS_ID is empty!"
          echo "NOTION_DATABASE_READING_ID=${{ secrets.NOTION_DATABASE_READING_ID }}" || echo "NOTION_DATABASE_READING_ID is empty!"

      - name: Set up .env file
        run: |
          echo "NEXT_PUBLIC_INSTAGRAM_ACCESS_TOKEN=${{ secrets.INSTAGRAM_ACCESS_TOKEN }}" > .env
          echo "NEXT_PUBLIC_GA_ID=${{ secrets.GA_ID }}" >> .env
          echo "NOTION_SECRET=${{ secrets.NOTION_SECRET }}" >> .env
          echo "NOTION_TOKEN_V2=${{ secrets.NOTION_TOKEN_V2 }}" >> .env
          echo "NOTION_USER_ID=${{ secrets.NOTION_USER_ID }}" >> .env
          echo "NOTION_DATABASE_DEVELOPMENT_I=${{ secrets.NOTION_DATABASE_DEVELOPMENT_ID }}" >> .env
          echo "NOTION_DATABASE_INSIGHTS_ID=${{ secrets.NOTION_DATABASE_INSIGHTS_ID }}" >> .env
          echo "NOTION_DATABASE_READING_ID=${{ secrets.NOTION_DATABASE_READING_ID }}" >> .env

      - name: Debug .env location
        run: cat .env || echo ".env file not found!"

      - name: Install dependencies
        run: npm install

      - name: List files in src/statics
        run: find ./src/statics

      - name: Clear Cache
        run: rm -rf .next

      - name: Build with Next.js
        timeout-minutes: 10
        run: npm run build

      - name: Add .nojekyll file
        run: echo > ./out/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
