name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Set up .env file
        run: echo "NEXT_PUBLIC_INSTAGRAM_ACCESS_TOKEN=${{ secrets.INSTAGRAM_ACCESS_TOKEN }}" > .env
      - name: Install dependencies
        run: npm install

      - name: List files in src/statics
        run: find ./src/statics
      - name: Check Development/_data file
        run: ls -l ./src/statics/Development/_data.ts || echo "File not found!"

      - name: Clear Cache
        run: rm -rf .next/cache
      - name: Build with Next.js
        run: NODE_ENV=production npm run build
      - name: Add .nojekyll file
        run: echo > ./out/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
